libffi-3.4.4.tar.gz:
  size: 1362394
  object_id: c164da33-8575-42d5-5bbe-44de72bd40b2
  sha: sha256:d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
python-3.10/Python-3.10.17.tgz:
  size: 25932824
  object_id: 1d8b2770-9c49-41eb-7db1-e07f453568cd
  sha: sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f
python-3.10/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
python-3.11/Python-3.11.12.tgz:
  size: 26575607
  object_id: 62b83070-c1d3-4335-420a-f5aa801e6c1f
  sha: sha256:379c9929a989a9d65a1f5d854e011f4872b142259f4fc0a8c4062d2815ed7fba
python-3.11/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
python-3.12/Python-3.12.10.tgz:
  size: 27122929
  object_id: b03cab6f-5fa4-4ed4-781b-013a0f2a8576
  sha: sha256:15d9c623abfd2165fe816ea1fb385d6ed8cf3c664661ab357f1782e3036a6dac
python-3.12/setuptools-67.7.2.tar.gz:
  size: 2491608
  object_id: 7ceac4d4-ea3b-4f5b-54a5-978ba76a8e5e
  sha: sha256:f104fa03692a2602fa0fec6c6a9e63b6c8a968de13e17c026957dd1f53d80990
sqlite-autoconf-3450200.tar.gz:
  size: 3234010
  object_id: 8b447cb8-3a5f-4a5a-782b-c5bb9462a9c8
  sha: sha256:bc9067442eedf3dd39989b5c5cfbfff37ae66cc9c99274e0c3052dc4d4a8f6ae
xz-5.6.3.tar.gz:
  size: 2279396
  object_id: 9de15318-81e4-429b-6874-9d8753ade144
  sha: sha256:b1d45295d3f71f25a4c9101bd7c8d16cb56348bbef3bbc738da0351e17c73317
